# Generated by Django 2.1.2 on 2018-10-11 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSDNBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=100)),
                ('writer', models.CharField(max_length=30)),
                ('read_count', models.IntegerField()),
                ('content', models.TextField()),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
