# Generated by Django 2.1.2 on 2018-10-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='csdnblog',
            name='writer_id',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
