# Generated by Django 2.1.2 on 2018-10-13 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0002_csdnblog_writer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csdnblog',
            name='url',
            field=models.CharField(max_length=100),
        ),
    ]
